// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuyQxWPtTpbla7AlMqMy1dI3L6r537ff4',
    appId: '1:407071090061:web:ddf85bafefc5aed8e789c4',
    messagingSenderId: '407071090061',
    projectId: 'flutter-shopping-list-a39c2',
    authDomain: 'flutter-shopping-list-a39c2.firebaseapp.com',
    databaseURL: 'https://flutter-shopping-list-a39c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-a39c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZD0eacN-pxoOLeCHNqFvfVJTwu_UT7nk',
    appId: '1:407071090061:android:14a3c2f5c1b058f5e789c4',
    messagingSenderId: '407071090061',
    projectId: 'flutter-shopping-list-a39c2',
    databaseURL: 'https://flutter-shopping-list-a39c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-a39c2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALjj8KGX9I9J82UJl55_19cpXNP3nuA3g',
    appId: '1:407071090061:ios:daa923a032208c10e789c4',
    messagingSenderId: '407071090061',
    projectId: 'flutter-shopping-list-a39c2',
    databaseURL: 'https://flutter-shopping-list-a39c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-a39c2.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALjj8KGX9I9J82UJl55_19cpXNP3nuA3g',
    appId: '1:407071090061:ios:daa923a032208c10e789c4',
    messagingSenderId: '407071090061',
    projectId: 'flutter-shopping-list-a39c2',
    databaseURL: 'https://flutter-shopping-list-a39c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-a39c2.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuyQxWPtTpbla7AlMqMy1dI3L6r537ff4',
    appId: '1:407071090061:web:91b6e6d9364eccace789c4',
    messagingSenderId: '407071090061',
    projectId: 'flutter-shopping-list-a39c2',
    authDomain: 'flutter-shopping-list-a39c2.firebaseapp.com',
    databaseURL: 'https://flutter-shopping-list-a39c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-shopping-list-a39c2.firebasestorage.app',
  );
}
